### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by Streammer** [jeffersonxavier/webrtc-example#1]
Where is this file from index.html   <script src="/socket.io/socket.io.js"></script> ?

**Comment by jeffersonxavier** [comment]
The socket.io is defined as a dependency in _package.json_. Just execute **npm install** to install all dependencies and the path _/socket.io/socket.io.js_ will be available in **node_modules**.

You can see this [commit](https://github.com/jeffersonxavier/webrtc-example/commit/38716e38f1bae8fbffe21c02844ebbe2854fbda5) to see more details of quickstart.

**Comment by Streammer** [comment]
![Screenshot 2022-10-14 at 10 31 41](https://user-images.githubusercontent.com/18185512/195788915-2e6182ab-75fa-43f3-9fb7-47e5d77869a9.png)

**Comment by Streammer** [comment]
Thanks
